# Generated by Django 3.2.19 on 2023-06-21 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата запроса координат'),
        ),
    ]
