FROM node:15.14.0-alpine

WORKDIR /app

COPY bundles-src ./bundles-src

COPY package*.json .

RUN npm install

# COPY . .

CMD ["./node_modules/.bin/parcel", "build", "bundles-src/index.js", "--dist-dir", "bundles", "--public-url", "./"]

