FROM python:3.9-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1 \
    PYTHONUNBUFFERED 1

COPY requirements.txt .

RUN  pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

RUN python manage.py collectstatic --no-input

