# Generated by Django 3.2.19 on 2023-06-04 09:35

from django.db import migrations


def set_order_products_price(apps, schema_editor):
    ProductInOrder = apps.get_model('foodcartapp', 'ProductInOrder')

    for product in ProductInOrder.objects.iterator():
        product.fixed_price = product.product.price
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230603_1758'),
    ]

    operations = [
        migrations.RunPython(set_order_products_price)
    ]
