# Generated by Django 3.2.19 on 2023-06-04 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230604_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='фиксированная стоимость'),
        ),
    ]
