# Generated by Django 3.2.19 on 2023-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RW', 'Необработанный'), ('PR', 'В ресторане'), ('DE', 'В доставке'), ('CO', 'Завершен')], db_index=True, default='RW', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
