# Generated by Django 3.2.19 on 2023-06-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(verbose_name='Комментарий к заказу'),
        ),
    ]
