version: '3.8'

services:
  db:
    restart: always
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ../.env

  frontend:
    ports:
      - "1234:1234"
    volumes:
      - ./bundles:/app/bundles
    build:
      context: ..
      dockerfile: ../Dockerfile.front

  django:
    volumes:
      - ./:/app
    container_name: django
    build:
      context: ..
      dockerfile: ../Dockerfile.back
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - frontend

volumes:
  postgres_data: null
