# Generated by Django 3.2.19 on 2023-06-04 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_productinorder_fixed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='фиксированная стоимость'),
        ),
    ]
