# Generated by Django 3.2.19 on 2023-06-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('RW', 'Необработанный'), ('PR', 'В ресторане'), ('DE', 'В доставке'), ('CO', 'Завершен')], max_length=2),
        ),
    ]
