# Generated by Django 3.2.19 on 2023-06-07 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 19, 35, 17, 428239, tzinfo=utc), verbose_name='Перезвонили клиенту'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 19, 35, 17, 428239, tzinfo=utc), verbose_name='Доставили клиенту'),
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Время заказа'),
        ),
    ]
