# Generated by Django 3.2.19 on 2023-06-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_order_cooking_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Необработанный'), ('B', 'В ресторане'), ('C', 'В доставке'), ('D', 'Завершен')], db_index=True, default='A', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
